# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Michael Nsiah-Nimo
description: "Hello, I'm Michael, a Data Scientist committed to leveraging data-driven insights for driving impactful business decisions. My portfolio features projects focused on translating data into actionable strategies with a strong emphasis on delivering tangible business outcomes. Feel free to explore my GitHub and LinkedIn profiles or download my resume using the provided links to delve deeper into my expertise and experience!"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "El Paso, Texas USA"
resume_url: /docs/Michael_Nsiah_Nimo_Resume_DSBI.pdf
avatar_image: /img/4f9792b0-b17f-4074-a995-e497061652be-removebg-preview Cropped.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/michael-nsiah-nimo-36494967/" # Add your linkedln handle
github: "https://github.com/mnsiahnimo"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

